---
- name: Create RKE2 Config Directory
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: 0755

- name: Copy RKE2 config
  ansible.builtin.template:
    src: "rke2-config.yaml.j2"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - "crimsonfez.rke2 : Restart RKE2 Agent"

- name: Start RKE2 agent service
  ansible.builtin.systemd:
    name: "rke2-agent.service"
    state: started
    enabled: true