---
- name: Create RKE2 Server Config Directory
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: 0755

- name: Setup ZFS Subvol
  community.general.zfs:
    name: "{{rke2_containerd_zfs_subvol}}"
    state: present
    extra_zfs_properties:
      mountpoint: /var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.zfs
  when: rke2_containerd_snapshotter == "zfs"

- name: Copy RKE2 config
  ansible.builtin.template:
    src: "rke2-config.yaml.j2"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - "crimsonfez.rke2 : Restart RKE2 Server"

- name: Start RKE2 service on the first server
  ansible.builtin.systemd:
    name: "rke2-server.service"
    state: started
    enabled: true

- name: "Configure Containerd `[plugins.cri] device_ownership_from_security_context`: Create tmpl"
  ansible.builtin.copy:
    remote_src: true
    src: /var/lib/rancher/rke2/agent/etc/containerd/config.toml
    dest: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
    backup: true

- name: "Configure Containerd `[plugins.cri] device_ownership_from_security_context`: Modify tmpl"
  ansible.builtin.lineinfile:
    line: "  device_ownership_from_security_context = true"
    insertafter: '\[plugins.\"io.containerd.grpc.v1.cri\"\]'
    path: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
    state: "{{ rke2_containerd_device_ownership_from_security_context | ternary('present', 'absent') }}"
  notify:
    - "crimsonfez.rke2 : Restart RKE2 Agent"