---
# handlers file for rke2
- name: Restart RKE2 Agent
  ansible.builtin.service:
    name: rke2-agent
    state: restarted
  when: rke2_restart

- name: Restart RKE2 Server
  ansible.builtin.service:
    name: rke2-server
    state: restarted
  when: rke2_restart